---
name: Alejandro Manuel Ferreiro
position: "Dr. en Ciencias Biológicas"
profilepic: "img/profile.jpg"
address: "Instituto de Diversidad y Ecología Animal (IDEA)"
www: aleferreiro.netlify.app
email: "aleferreiro7@gmail.com"
twitter: aleferreiro1
github: aleferreiro
linkedin: alejandro-manuel-ferreiro-431aa4b0
orcid: 0000-0002-0921-6137
headcolor: 2b8cbe
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(here)
```

```{r functions}
readExcelSheets <- function(filename){
  # read all sheets in .xlsx 
  all <- readxl::excel_sheets(filename)
  
  # import each sheet into a list using readxl::read_excel
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  
  # save sheet name for each sheet (list)
  names(list) <- all
  
  # breaks up list and creates a dataframe for each sheet with df names matching sheet names
  list2env(list, envir = .GlobalEnv)
}
```
```{r load-data, message=F, results='hide'}
filename <- here::here("ferreiro_vitae_data_es.xlsx")
readExcelSheets(filename)
```
# Educación
```{r}
education %>% 
  detailed_entries(what = institution,
                   when = year,
                   with = degree,
                   where = where,
                   why = details)
```

# Publicaciones en revistas científicas
```{r}
library(rorcid)
library(tidyverse)
out <- works(orcid_id("0000-0002-0921-6137")) 
 tibble(
   Journal = out$`journal-title.value`,
   Title = out$title.title.value,
   Year = out$`publication-date.year.value`,
   DOI = c(out[[21]][[1]][1,2], out[[21]][[2]][1,2])
 ) %>% 
  detailed_entries(
  DOI,
  Journal,
  Title,
  Year
)
```

# Otras publicaciones
```{r}
bibliography_entries(here("otherPubs.bib"))
```

# Manuscritos enviados
```{r}
msSubmitted %>% 
  detailed_entries(what = status,
                   when = journal,
                   with = title,
                   where = ,
                   why = )
```


# Premios, becas y subsidios
```{r}
awards %>% 
  detailed_entries(what = institution,
                   when = date,
                   with = name,
                   where = role,
                   why = details)
```

# Cursos realizados
```{r}
courses %>% 
  detailed_entries(what = institution,
                   when = date,
                   with = name,
                   where = where,
                   why = details)
```

# Otras capacitaciones
```{r}
otherCourses %>% 
  detailed_entries(what = institution,
                   when = date,
                   with = name,
                   where = where)
```

# Docencia
```{r}
teaching %>% 
  detailed_entries(what = institution,
                   when = date,
                   with = name,
                   where = where,
                   why = details)
```

# Cargos de gestión
```{r}
management %>% 
  detailed_entries(what = institution,
                   when = date,
                   with = name,
                   where = where)
```

# Habilidades
## Técnicas

```{r}
skills %>% 
  detailed_entries(what = skill,
                   with = group)
```

## Idiomas
```{r}
language %>% 
  detailed_entries(what = level,
                   with = language)
```
